"""removing unused fields

Revision ID: 659af050daab
Revises: f654adfab2c1
Create Date: 2025-06-19 21:24:39.644228
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '659af050daab'
down_revision: Union[str, None] = 'f654adfab2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f('nuvie_patients_SSN_unique'),
        'nuvie_patients',
        ['SSN'],
        schema='nuvie',
    )
    op.drop_column('nuvie_patients', 'height_cm', schema='nuvie')
    op.drop_column('nuvie_patients', 'last_name', schema='nuvie')
    op.drop_column('nuvie_patients', 'last_updated', schema='nuvie')
    op.drop_column('nuvie_patients', 'occupation', schema='nuvie')
    op.drop_column('nuvie_patients', 'email', schema='nuvie')
    op.drop_column('nuvie_patients', 'first_name', schema='nuvie')
    op.drop_column('nuvie_patients', 'weight_kg', schema='nuvie')
    op.drop_column('nuvie_patients', 'phone_number', schema='nuvie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'nuvie_patients',
        sa.Column(
            'phone_number', sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        schema='nuvie',
    )
    op.add_column(
        'nuvie_patients',
        sa.Column(
            'weight_kg',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema='nuvie',
    )
    op.add_column(
        'nuvie_patients',
        sa.Column(
            'first_name', sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        schema='nuvie',
    )
    op.add_column(
        'nuvie_patients',
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
        schema='nuvie',
    )
    op.add_column(
        'nuvie_patients',
        sa.Column(
            'occupation', sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        schema='nuvie',
    )
    op.add_column(
        'nuvie_patients',
        sa.Column(
            'last_updated',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        schema='nuvie',
    )
    op.add_column(
        'nuvie_patients',
        sa.Column(
            'last_name', sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        schema='nuvie',
    )
    op.add_column(
        'nuvie_patients',
        sa.Column(
            'height_cm',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema='nuvie',
    )
    op.drop_constraint(
        op.f('nuvie_patients_SSN_unique'),
        'nuvie_patients',
        schema='nuvie',
        type_='unique',
    )
    # ### end Alembic commands ###
