"""uploading project structure

Revision ID: f654adfab2c1
Revises:
Create Date: 2025-06-19 19:14:51.677805
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f654adfab2c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nuvie_patients',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=True,
        ),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('birth_date', sa.DateTime(), nullable=False),
        sa.Column('death_date', sa.DateTime(), nullable=True),
        sa.Column('SSN', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            'first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            'last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            'self_declared_color',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            'civil_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column('income', sa.Float(), nullable=True),
        sa.Column(
            'address', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            'zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            'phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('height_cm', sa.Float(), nullable=True),
        sa.Column('weight_kg', sa.Float(), nullable=True),
        sa.Column(
            'occupation', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            'healthcare_coverage',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('nuvie_patients_pkey')),
        schema='nuvie',
    )
    op.create_table(
        'nuvie_users',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=True,
        ),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column(
            'password', sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            'user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('nuvie_users_pkey')),
        schema='nuvie',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nuvie_users', schema='nuvie')
    op.drop_table('nuvie_patients', schema='nuvie')
    # ### end Alembic commands ###
